development:
  :concurrency: 5
production:
  :concurrency: 4 # 8 - 2 for sidekiq internals - 2 for ActionCable (?)
:queues:
  - [paperclip, 1]
  - [messages, 2]
  - [suggestions, 2]
  - [users, 2]
  - default
